### ISSUE TITLE
HiDPI support

### ISSUE THREAD

**Issue by miabrahams** [mitchcapper/wpfdoist#1]
My desktop setup uses a 3840x2160 monitor with a 1920x1080 next to it. This uses Windows HiDPI automatic scaling. The typeface in the app appears very small on either monitor.

**Comment by mitchcapper** [comment]
Did you try hitting control + + (control plus +) to zoom in?
~mitch

**Comment by mitchcapper** [comment]
Please re-open if that did not fix your problem.

**Comment by miabrahams** [comment]
It's an alright fix temporarily.  There are some issues with the font size in the date entry field. It's also inconvenient to have to zoom in every time I start the program.
